### ISSUE TITLE
Förbättra Användarfeedback

### ISSUE THREAD

**Issue by clundqvi96** [clundqvi96/parkingPlanner#23]
Beskrivning: Ge bättre användarfeedback när åtgärder utförs (t.ex. bokning av nyckel, återlämning av nyckel). Detta kan inkludera laddningsindikatorer, framgångsmeddelanden eller felmeddelanden.
Acceptanskriterier:
Användare får omedelbar feedback när de utför en åtgärd.
Feedback inkluderar laddningsindikatorer, framgångsmeddelanden eller felmeddelanden efter behov.

**Comment by agnetabq** [comment]
Ställen där det behövs bättre feedback:
- Inloggning med ogiltig användare / ogitligt lösenord
